/// Product Card Dimen
const PRODUCT_CARD_WIDTH = 120.0;
const FAVORITE_ICON_BTN_HEIGHT = 40.0;
const FAVORITE_ICON_BTN_WIDTH = 40.0;
const CARD_LEFT_POSITION_PADDING = 100.0;
const PRODUCT_CARD_RADIUS = 20.0;